### ISSUE TITLE
 if ((1 == 0)) abort();

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#154]
clang-11: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
		pygtftk/stats/multiprocessing/multiproc.c:3395:31: warning: code will never be executed [-Wunreachable-code]
		                if ((1 == 0)) abort();
		                              ^~~~~
		pygtftk/stats/multiprocessing/multiproc.c:3395:22: note: silence by adding parentheses to mark code as explicitly dead
		                if ((1 == 0)) abort();
		                     ^
		                     /* DISABLES CODE */ ( )
		pygtftk/stats/multiprocessing/multiproc.c:3738:97: warning: unused function '__pyx_f_7pygtftk_5stats_15multiprocessing_9multiproc_example_func' [-Wunused-function]
		static struct __pyx_t_7pygtftk_5stats_15multiprocessing_17multiproc_structs_FUNC_2DARRAY_RESULT __pyx_f_7pygtftk_5stats_15multiprocessing_9multiproc_example_func(PY_LONG_LONG *__pyx_v_arr, PY_LONG_LONG *__pyx_v_shape, PY_LONG_LONG __pyx_v_parameter) {

**Comment by qferre** [comment]
As I said to you IRL, I believe those are inconsequential and just a quirk of Cython.

**Comment by dputhier** [comment]
Yes but I definitely don't like it...

**Comment by qferre** [comment]
Through a quick Google search, it has appeared in at least one other GitHub repository containing Cython code.
Besides, it is a self contained C statement : `if ((1 == 0)) abort();` so it essentially does nothing since there is a semicolon at the end.

We can keep the issue open until we figure it out, but I believe we have nothing to worry about.

**Comment by dputhier** [comment]
Will reopen this issue if needed.
