### ISSUE TITLE
Install error on ubuntu 20.04

### ISSUE THREAD

**Issue by samanthaconte** [dputhier/pygtftk#175]
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - pygtftk -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

**Comment by dputhier** [comment]
Need to check whether this is fixed with 1.6.0

**Comment by dputhier** [comment]
See #159 

        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda install -c bioconda pygtftk python=3.9

"""
It is failing because pygtftk, like many bioconda packages, also relies on conda-forge channel.
You should add the channels in this order:
https://github.com/dputhier/pygtftk#installation-through-conda-package-building

It will solve the issue for pygtftk and those packages.

Alternatively, you can ignore the configured channels and install packages using a file like this :
https://github.com/guillaumecharbonnier/mw-lib/blob/master/src/snakemake/envs/pygtftk.yaml
and use
"""
