### ISSUE TITLE
[ologram] almost all p-values set to p=1.11e-16

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#55]
Just want to point out this point that need to be checked. It is strange to get the same p-val for almost all features (p=1.11e-16).

gtftk peak_anno -i pygtftk/data/mini_real/mini_real.gtf.gz -o toto -c pygtftk/data/mini_real/hg38.genome -p pygtftk/data/mini_real/ENCFF112BHN_H3K4me3_K562_sub.bed -V 3

**Comment by qferre** [comment]
This is due to floating point precision in the log functions.

This can be demonstrated by considering the function `nf.log_nb_pval(k, mean, var)` which gives the log of the p value of k for a Neg Binom distribution of parameters mean and var :

```
log_nb_pval(1000, 2, 4)
>>> -36.7368005696771
log_nb_pval(10000000000000000, 2, 4)
>>> -36.7368005696771
```
And incidentally, exp(-36.7368005696771) is roughly 1.11E-16...

**Comment by qferre** [comment]
I will mitigate this by writing "p<1.11E-16" instead of "p=1.11E-16" on the graphs when applicable.

**Comment by qferre** [comment]
Done in commit 668533a77c0684527a4e25e9dd9c2b11565abe81.
Closing.

**Comment by qferre** [comment]
I am reopening this issue to keep track of the new methods implemented to calculate the p-value.
After a stint using integral approximation, we now have the same method as in R (currently in **develop** branch) using a Beta approximation outlines in "Numerical Recipes in C : the Art of Scientific Computing" ever since ed6dd062cf14a04107de46d7f90c01741ae98d22

**Comment by qferre** [comment]
The Beta approximation used is now based on the GNU scientific library instead, since 749af33d0c2646f9f6eb7b919b3be06f9f879c2e, for licensing reasons. I have checked its accuracy by comparing it to R. Closing this.
