### ISSUE TITLE
Replace minibatch-nb and minibatch-size with max-ram

### ISSUE THREAD

**Issue by guillaumecharbonnier** [dputhier/pygtftk#82]
I feel we could replace these two technical arguments with a more user-friendly "--max-ram" argument with some benchmarking to find the appropriate extrapolation function depending on input files.
Even better (?), the algorithm could :
1. memory-ologram <- check memory used by ologram after loading of all files.
2. send one batch.
3. memory-batch <- check the batch memory consumption.
4. send n other batch in order to have memory-ologram + n * memory-batch ~< max-ram

**Comment by qferre** [comment]
The problem is that the RAM footprint depends on the features. Even with batches of the same size, the memory cost will be different when processing 'exons' than when processing 'start_codon'. 

Making a dynamic batch size would be possible, as the function to produce each batch runs independantly, but require some refactoring.
