### ISSUE TITLE
User-friendly adjustements to exposed arguments

### ISSUE THREAD

**Issue by guillaumecharbonnier** [dputhier/pygtftk#83]
I feel we could make ologram easier for new users with these small modifications:

Remove these arguments and display only warnings when conditions are met:
```
 -z, --no-gtf                No gtf file is provide as input. (default: False)
 -f, --force-chrom-gtf       Discard silently, from GTF, genes outside chromosomes defined in --chrom-info. (default: False)
 -w, --force-chrom-peak      Discard silently, from --peak-file, peaks outside chromosomes defined in --chrom-info. (default: False)
 -q, --force-chrom-more-bed  Discard silently, from --more-bed files, regions outside chromosomes defined in --chrom-info. (default: False)
```

Replace this argument:
```
 -if, --user-img-file        Provide an alternative path for the main image. (default: None)
```
by this:
```
 -pf, --pdf-file        Provide an alternative path for the main image. (default: None)
```
in order to be consistent with the two arguments above:
```
-pw, --pdf-width            Output pdf file width (inches). (default: None)
-ph, --pdf-height           Output pdf file height (inches). (default: None)
```

Why would you want to skip image producing? Is it time consuming? Remove this argument? :
```
 -x, --no-pdf                Do not produce any image file. (default: False)
```

Move this argument:
```
 -dpi, --dpi                 Dpi to use. (default: 300)
```
with other plot-related arguments and maybe adjust name in consequence? -pd, --pdf-dpi? 
Side-note: I am surprised you have to rasterize your pdf as the plots are not very complex.

Last but not least, hide this argument:
```
-pp, --pval-precision       Precision of p-val calculation in dps. (default: 1500)
```
@qferre I know your struggle with beta function and integral calculation, but no end-user can endure what you did. You need to be our silent guardian, our watchful protector. Our dark knight.

**Comment by dputhier** [comment]
Hi Guillaume,
Regarding -fwq we may discard this arguments. We would thus print a warning
when required. The problem is that if the GTF and chrominfo file contain
totally different chromosomes (e.g w/ or w/o chr) the program will end up
with an empty GTF and throw an error message (this one will be less self
explaining regarding the initial problem). So it's not clear to me whether
we should go this way.
Regarding -z, it is more tricky. Currently we are expecting a GTF from file
or stdin. If no argument tells us internally that no GTF is expected then
we will wait until a signal comes from stdin. So if we discard -z we have
to discard default value to stdin for -i (if I remember well about the
code).

**Comment by qferre** [comment]
The p-val precision parameter is now hidden in 243db30524bebc51d3958abc32ce3c232876dbbd :)

**Comment by dputhier** [comment]
I guess -dpi is a relic from png format (that was used before). I will delete it.

**Comment by dputhier** [comment]
I have deleted --dpi and changed --img-user-file to --pdf-file in 4fd3cd7e9ccf7bf5975cb178269e7cfcbbd9bd40
